// Autogenerated with DRAKON Editor 1.31

package main

import ("fmt")





func  bubbleSort(ar []int)  {
    // item 140001
    i := 0;
    for {
        // item 140002
        if i < len(ar) {
            
        } else {
            break
        }
        // item 160001
        j := 0;
        for {
            // item 160002
            if j < len(ar) {
                
            } else {
                break
            }
            // item 18
            if ar[i] < ar[j] {
                // item 21
                ar[i],ar[j] = ar[j],ar[i]
            } else {
                
            }
            // item 160003
            j++;
        }
        // item 140003
        i++;
    }
}

func  main()  {
    // item 12
    ar := []int{90, 11, 81, 21,
    71,  31, 61, 41, 51, 10}
    // item 13
    bubbleSort(ar)
    // item 26
    fmt.Println("Input array --->", ar)
    bubbleSort(ar)
    fmt.Println("Output array --->", ar)
}


