// Autogenerated with DRAKON Editor 1.31

package main

import "fmt"



func  heapRoot(size int, ar []int, i int) []int {
    // item 42
    left  := i*2 + 1
    right := i*2 + 2
    var max int = i
    // item 43
    if left < size && 
ar[left] > ar[max] {
        // item 46
        max = left
    } else {
        
    }
    // item 47
    if right < size && 
ar[right] > ar[max] {
        // item 50
        max = right
    } else {
        
    }
    // item 62
    if max != i {
        // item 65
        ar[i],ar[max] = ar[max],ar[i]
        // item 66
        heapRoot(size,ar,max)
    } else {
        
    }
    // item 58
    return ar
}

func  heapSort(ar []int) []int {
    // item 19
    size := len(ar)
    // item 20
    i0 := size/2 - 1
    // item 210001
    i := i0;
    for {
        // item 210002
        if i >= 0 {
            
        } else {
            break
        }
        // item 23
        heapRoot(size, ar, i)
        // item 210003
        i--;
    }
    // item 240001
    i = size - 1;
    for {
        // item 240002
        if i > 0 {
            
        } else {
            break
        }
        // item 26
        ar[0],ar[i] = ar[i],ar[0] 
        size--
        // item 27
        heapRoot(size,ar,0)
        // item 240003
        i--;
    }
    // item 57
    return ar
}

func  main()  {
    // item 4
    arr:= []int{11, 32, 23, 74, 
    85, 90, 62, 48,53, 10}
    fmt.Println("Input array", arr)
    heapSort(arr)
    fmt.Println("Щгput array", arr)
}


