// Autogenerated with DRAKON Editor 1.31

package main
import ("fmt")






func  insertionSort(ar [] int)  {
    // item 6
    size := len(ar)
    // item 70001
    i := 1;
    for {
        // item 70002
        if i < size {
            
        } else {
            break
        }
        // item 100001
        j := i;
        for {
            // item 100002
            if (j > 0) && (ar[j] < ar[j-1]) {
                
            } else {
                break
            }
            // item 12
            ar[j],ar[j-1] = ar[j-1], ar[j]
            // item 100003
            j--;
        }
        // item 70003
        i++;
    }
}

func  main()  {
    // item 21
    ar := []int{90, 11, 81, 21, 71, 
    31, 61, 41, 51, 10}
    // item 20
    fmt.Println("Input array -->", ar)
    insertionSort(ar)
    fmt.Println("Output array -->", ar)
}


