// Autogenerated with DRAKON Editor 1.31

package main
import (
    "fmt"
)



func  main()  {
    // item 5
    arr:= []int{11, 32, 23, 74, 
    85, 90, 62, 48,53, 10}
    // item 54
    fmt.Println(arr)
    // item 6
    fmt.Println(mergeSort(arr))
}

func  merge(a [] int, b [] int) []int {
    // item 13
    size := len(a)+len(b)
    // item 23
    i,j := 0,0
    // item 12
    result := make([]int, size)
    // item 140001
    k := 0;
    for {
        // item 140002
        if k < size {
            
        } else {
            break
        }
        // item 250001
        if true == (i == len(a)) {
            // item 32
            result[k] = b[j]
            j += 1
        } else {
            // item 250002
            if true == (j == len(b)) {
                // item 33
                result[k] = a[i]
                i += 1
            } else {
                // item 250003
                if true == (a[i] >= b[j]) {
                    // item 34
                    result[k] = b[j]
                    j += 1
                } else {
                    // item 250004
                    if true == (a[i] < b[j]) {
                        // item 38
                        result[k] = a[i]
                        i += 1
                    } else {
                        
                    }
                }
            }
        }
        // item 140003
        k++;
    }
    // item 42
    return result
}

func  mergeSort(numbers []int) []int {
    // item 49
    if len(numbers) < 2 {
        // item 48
        return numbers
    } else {
        
    }
    // item 52
    middle := int(len(numbers) / 2)
    // item 53
    return merge(mergeSort(numbers[middle:]),
     mergeSort(numbers[:middle]))
}


