// Autogenerated with DRAKON Editor 1.31

package main

import (
	"fmt"
)




func  main()  {
    // item 4
    ar := []int{78, 11, 81, 21, 71,
    31, 61, 41, 51, 24}
    fmt.Println("Input array -->", ar)
    quickSort(ar)
    fmt.Println("Output array -->", ar)
}

func  partition(ar []int) int {
    // item 18
    pivot := ar[len(ar)/2]
    // item 350001
    k := 0;
    for {
        // item 350002
        if k < len(ar)+1 {
            
        } else {
            break
        }
        // item 190001
        left := 0;
        for {
            // item 190002
            if ar[left] < pivot {
                
            } else {
                break
            }
            // item 190003
            left++;
        }
        // item 220001
        right := len(ar) - 1;
        for {
            // item 220002
            if ar[right] > pivot {
                
            } else {
                break
            }
            // item 220003
            right--;
        }
        // item 25
        if left >= right {
            // item 24
            return right
        } else {
            
        }
        // item 28
        ar[left],ar[right] = 
        ar[right],ar[left]
        // item 350003
        k++;
    }
    // item 37
    return 0
}

func  quickSort(ar []int)  {
    // item 9
    if len(ar) <= 1 {
        // item 8
        return
    } else {
        
    }
    // item 12
    split := partition(ar)
    // item 13
    quickSort(ar[:split])
    // item 14
    quickSort(ar[split:])
}


