// Autogenerated with DRAKON Editor 1.31

package main

import ("fmt")





func  main()  {
    // item 12
    ar := []int{90, 11, 81, 21, 71, 
    31, 61, 41, 51, 10}
    // item 13
    fmt.Println("Input array --> ", ar)
    selectSort(ar)
    fmt.Println("Output array --> ", ar)
}

func  selectSort(ar []int)  {
    // item 140001
    i := 0;
    for {
        // item 140002
        if i < len(ar) {
            
        } else {
            break
        }
        // item 34
        min := i
        // item 160001
        j := i + 1;
        for {
            // item 160002
            if j < len(ar) {
                
            } else {
                break
            }
            // item 18
            if ar[min] > ar[j] {
                // item 21
                min = j
            } else {
                
            }
            // item 160003
            j++;
        }
        // item 35
        if min != i {
            // item 38
            //swap(ar, i, min)
            ar[i],ar[min] = ar[min],ar[i]
        } else {
            
        }
        // item 140003
        i++;
    }
}

func  swap(ar [] int, k,l int)()  {
    // item 33
    temp := ar[k]
    ar[k] = ar[l]
    ar[l] = temp
}


