// Autogenerated with DRAKON Editor 1.31

package main
import "fmt"



func  main()  {
    // item 4
    list := []int{90, -80, 70, -60, 
    50, -40, 30, -20, 10, 0}
    fmt.Println("Input array -->", list)
    shellSort(list)
    fmt.Println("Output array -->", list)
}

func  shellSort(list []int)  {
    // item 19
    var j int
    // item 100001
    inc := len(list) / 2;
    for {
        // item 100002
        if inc > 0 {
            
        } else {
            break
        }
        // item 120001
        i := inc;
        for {
            // item 120002
            if i < len(list) {
                
            } else {
                break
            }
            // item 14
            temp := list[i]
            // item 150001
            j = i;
            for {
                // item 150002
                if j >= inc && list[j-inc] > temp {
                    
                } else {
                    break
                }
                // item 17
                list[j] = list[j-inc]
                // item 150003
                j -= inc;
            }
            // item 18
            list[j] = temp
            // item 120003
            i++;
        }
        // item 100003
        inc = (inc + 1) * 5 / 11;
    }
}


