// Autogenerated with DRAKON Editor 1.31

package main

import "fmt"

type Graph struct {
	size int
	nodes map[int][]int
}



func  (g *Graph) addEdge(start, last int)  {
    // item 29
    if start >= 0 && start < g.size && 
last >= 0 && last < g.size {
        // item 12
        g.nodes[start] = 
        append(g.nodes[start], last)
    } else {
        // item 32
        fmt.Println("\nError")
    }
}

func  (g *Graph) bfsGraph(start int)  {
    // item 50
    visited := make(map[int]bool)
    // item 51
    queue := []int{start}
    for {
        // item 55
        node := queue[0]
        // item 56
        queue = queue[1:]
        // item 57
        if visited[node] {
            // item 60
            continue
        } else {
            
        }
        // item 61
        fmt.Printf("%d ", node)
        // item 62
        visited[node] = true
        for _, neighbor := range g.nodes[node] {
            // item 65
            if !visited[neighbor] {
                // item 68
                queue = append(queue, neighbor)
            } else {
                
            }
        }
        // item 52
        if len(queue) <= 0 {
            break
        } else {
            
        }
    }
}

func  (g *Graph) dfsGraph(start int, visited map[int]bool)  {
    // item 38
        visited[start] = true
        fmt.Printf("%d ", start)
    for _, neighbor := range g.nodes[start] {
        // item 41
        if !visited[neighbor] {
            // item 44
            g.dfsGraph(neighbor, visited)
        } else {
            
        }
    }
}

func  (g *Graph) printAdjacencyList()  {
    for node, neighbors := range g.nodes {
        // item 18
        fmt.Printf("%d: node = ", node)
        for _, neighbor := range neighbors {
            // item 21
            fmt.Printf("%d ", neighbor)
        }
        // item 22
        fmt.Println()
    }
}

func  NewGraph() *Graph {
    // item 6
    return &Graph{
    nodes: make(map[int][]int),
    }
}

func  main()  {
    // item 85
    graph := NewGraph()
    graph.size = 6
    // item 86
    graph.addEdge(0, 1)
    graph.addEdge(0, 5)
    graph.addEdge(1, 1)
    graph.addEdge(2, 1)
    graph.addEdge(3, 0)
    graph.addEdge(3, 3)
    graph.addEdge(4, 2)
    graph.addEdge(4, 3)
    graph.addEdge(5, 1)
    // item 87
    graph.printAdjacencyList()
    // item 89
     fmt.Println("Depth First Search:")
     visited := make(map[int]bool)
    for node := range graph.nodes {
        // item 92
        if !visited[node] {
            // item 95
            graph.dfsGraph(node, visited)
        } else {
            
        }
    }
    // item 96
    fmt.Println("BFS traversal:")
    // item 97
    graph.bfsGraph(4)
}


