#!/usr/bin/env python
# coding: utf-8

# Autogenerated with DRAKON Editor 1.31

def Search_minmax(my_list):
    #item 6
    minim=my_list[0]
    maxim=my_list[0]
    high=len(my_list)
    #item 70001
    i=1
    while True:
        #item 70002
        if i<high:
            pass
        else:
            break
        #item 9
        if my_list[i] < minim:
            #item 12
            minim=my_list[i]
        else:
            pass
        #item 15
        if my_list[i] > maxim:
            #item 18
            maxim=my_list[i]
        else:
            pass
        #item 70003
        i=i+1
    #item 19
    print('minim=',minim)
    print('maxim=',maxim)
    #item 14
    return minim,maxim

min=[6,3,1,2,8,22]
Search_minmax(min)
