// Autogenerated with DRAKON Editor 1.31

package main

import "fmt"



func  main()  {
    // item 4
    arr := []int{1, 2, 3, 4, 5, 6}
    fmt.Println(arr)
    // item 5
    lns := len(arr)
    fmt.Println("Длина = ", lns)
    // item 60001
    i := 0;
    for {
        // item 60002
        if i < (lns-1)/2 {
            
        } else {
            break
        }
        // item 8
        arr[i], arr[lns-i-1] = arr[lns-i-1], arr[i]
        // item 60003
        i++;
    }
    // item 9
    fmt.Println(arr)
}


