// Autogenerated with DRAKON Editor 1.31

package main
import (
	"fmt"
)




func  dataSorted(data [] int, value int)  {
    // item 6
    size := len(data)
    // item 70001
    i := 0;
    for {
        // item 70002
        if i < size {
            
        } else {
            break
        }
        // item 10
        if data[i] >= value {
            // item 13
            fmt.Println("The element value -->", value)
            // item 14
            return
        } else {
            
        }
        // item 70003
        i++;
    }
}

func  main()  {
    // item 18
    data := []int {2,4,21,34,43,48,51,56,63}
    // item 19
    fmt.Println("Input data -->", data)
    var value int = 34
    // item 20
    dataSorted(data, value)
}


